/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rado.pripomienkovac;

import java.sql.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author ja
 */
public class AddUI extends javax.swing.JDialog {

    private Boolean editujeme;
    private Integer editId;
    
    public AddUI(java.awt.Frame parent, boolean modal, Boolean bEdit, Integer editId)  {
        super(parent, modal);
        initComponents();
        
        this.editujeme = bEdit;
        this.editId = editId;
        
        if (bEdit) {
            this.setTitle("Editovat zaznam");
            zobrazZaznam(this.editId);
        } else {
            this.setTitle("Pridat zaznam");
            DataDate dnes = DataDate.getToday();
            jTextField1.setText(String.valueOf(dnes.day));
            jTextField2.setText(String.valueOf(dnes.month));
            jTextField3.setText(String.valueOf(dnes.year));
            
            jTextArea1.setText("");
        }
        
        DocumentListener valLis = new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                validateDate();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                validateDate();
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                validateDate();
            }
        };
        
        jTextField1.getDocument().addDocumentListener(valLis);
        jTextField2.getDocument().addDocumentListener(valLis);
        jTextField3.getDocument().addDocumentListener(valLis);
    }
    
    private void zobrazZaznam(Integer id) {
        Note n = Note.notes.get(id.intValue());
        //@FIXME ak sa nenachadza key
        if (n.content instanceof ContentTitleString) {
            jTextField4.setText(((ContentTitleString)n.content).getTitle());
            jTextArea1.setText(((ContentTitleString)n.content).getString());
        } else if (n.content instanceof ContentSimpleString) {
            jTextArea1.setText(((ContentSimpleString)n.content).getString());
            
        }
        if (n.trigger instanceof TriggerSimpleDate) {
            DataDate datum = ((TriggerSimpleDate)n.trigger).datum;
            jTextField1.setText(String.valueOf(datum.day));
            jTextField2.setText(String.valueOf(datum.month));
            jTextField3.setText(String.valueOf(datum.year));
        }
    }
    
    private void pridajZaznam() throws SietkaException, SQLException {
        // aggregating form data
        int day = Integer.valueOf(jTextField1.getText());
        int mon = Integer.valueOf(jTextField2.getText());
        int year = Integer.valueOf(jTextField3.getText());
        
        String obsah = jTextArea1.getText();
        String title = jTextField4.getText();
        
        DataDate datum;
        try {
            datum = new DataDate(year, mon, day);
        } catch (ExceptionMyDateInvalid ex) {
            throw new RuntimeException("datum not validated");
        }
        Note.add(
                new TriggerSimpleDate(datum),
                new ContentTitleString(title, obsah));
    }
    
    private void zeditujZaznam() throws SietkaException, SQLException {
        // aggregating form data
        int day = Integer.valueOf(jTextField1.getText());
        int mon = Integer.valueOf(jTextField2.getText());
        int year = Integer.valueOf(jTextField3.getText());
        
        String obsah = jTextArea1.getText();
        String title = jTextField4.getText();
        
        DataDate datum;
        try {
            datum = new DataDate(year, mon, day);
        } catch (ExceptionMyDateInvalid ex) {
            throw new RuntimeException("datum not validated");
        }
        
        Note.edit(editId, new TriggerSimpleDate(datum), new ContentTitleString(title, obsah));
    }

    private void validateDate() {
        try {
            int day = Integer.valueOf(jTextField1.getText());
            int mon = Integer.valueOf(jTextField2.getText());
            int year = Integer.valueOf(jTextField3.getText());
            new DataDate(year, mon, day);
            
            jButton1.setEnabled(true);
        } catch (ExceptionMyDateInvalid  ex) {
            jButton1.setEnabled(false);
        } catch (Exception ex) {
            jButton1.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pripomienka"));

        jLabel1.setText("deň");

        jTextField1.setText("18");

        jTextField2.setText(" 4");

        jLabel2.setText("mesiac");

        jLabel3.setText("rok");

        jTextField3.setText("2013");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(jTextField4)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            if (editujeme) {
                zeditujZaznam();
            } else {
                pridajZaznam();
            }
        } catch (SietkaException ex) {
            ObecneFunkcie.chybakonci("Error with editing/adding record");
        } catch (SQLException ex) {
            ObecneFunkcie.chybakonci("Error with editing/adding record SQL");
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
